"""
addSlicer — add a slicer to filter a PivotTable or Table.

Uses Excel's VBA/COM SlicerCaches.Add2 + Slicers.Add. Requires the source
object (PivotTable or ListObject) to already exist. The source can be
referenced by name across the workbook.
"""

from __future__ import annotations

from typing import Any

from app.execution.base import ExecutorContext
from app.execution.capability_registry import registry


def _find_pivot_by_name(book: Any, name: str) -> Any:
    """Scan every sheet for a PivotTable with the given name."""
    for sheet in book.sheets:
        try:
            pivots = sheet.api.PivotTables()
            # PivotTables is iterable via its .Count / .Item interface.
            count = pivots.Count
            for i in range(1, count + 1):
                pt = pivots.Item(i)
                if pt.Name == name:
                    return pt
        except Exception:  # noqa: BLE001
            continue
    return None


def _find_table_by_name(book: Any, name: str) -> Any:
    """Scan every sheet for a ListObject (Table) with the given name."""
    for sheet in book.sheets:
        try:
            lobjs = sheet.api.ListObjects
            count = lobjs.Count
            for i in range(1, count + 1):
                lo = lobjs.Item(i)
                if lo.Name == name:
                    return lo
        except Exception:  # noqa: BLE001
            continue
    return None


def handler(ctx: ExecutorContext, params: dict[str, Any]) -> dict[str, Any]:
    source_type = params.get("sourceType") or "pivotTable"
    source_name = params.get("sourceName")
    source_field = params.get("sourceField")
    sheet_name = params.get("sheetName")
    left = params.get("left")
    top = params.get("top")
    width = params.get("width")
    height = params.get("height")

    if not source_name or not source_field:
        return {
            "status": "error",
            "message": "addSlicer requires 'sourceName' and 'sourceField'.",
        }

    if ctx.dry_run:
        return {
            "status": "preview",
            "message": f"Would add slicer for {source_field!r} on {source_name!r}.",
        }

    book = ctx.workbook_handle
    try:
        # 1. Resolve the slicer source object.
        if source_type == "table":
            source_obj = _find_table_by_name(book, source_name)
            if source_obj is None:
                return {
                    "status": "error",
                    "message": f"Table {source_name!r} not found in workbook.",
                }
        else:
            source_obj = _find_pivot_by_name(book, source_name)
            if source_obj is None:
                return {
                    "status": "error",
                    "message": f"PivotTable {source_name!r} not found in workbook.",
                }

        # 2. Destination sheet — default to the source's sheet.
        if sheet_name:
            try:
                dest_sheet = book.sheets[sheet_name]
            except Exception:
                return {
                    "status": "error",
                    "message": f"Sheet {sheet_name!r} not found. Please check the sheet name.",
                }
        else:
            dest_sheet = book.sheets.active

        # 3. Create the SlicerCache, then the Slicer.
        # SlicerCaches.Add2(Source, SourceField) — Add2 is the modern form
        # that supports both PivotTables and Tables.
        cache = book.api.SlicerCaches.Add2(source_obj, source_field)

        # Slicers.Add(SlicerDestination, Level, Name, Caption, Top, Left, Width, Height)
        # Level, Name, Caption are optional and auto-generated by Excel.
        add_kwargs: dict[str, Any] = {"SlicerDestination": dest_sheet.api}
        if top is not None:
            add_kwargs["Top"] = top
        if left is not None:
            add_kwargs["Left"] = left
        if width is not None:
            add_kwargs["Width"] = width
        if height is not None:
            add_kwargs["Height"] = height

        slicer = cache.Slicers.Add(**add_kwargs)
    except Exception as exc:  # noqa: BLE001
        return {
            "status": "error",
            "message": f"Add slicer failed: {exc}",
            "error": str(exc),
        }

    slicer_name = None
    try:
        slicer_name = slicer.Name
    except Exception:  # noqa: BLE001
        slicer_name = source_field

    on_sheet = f" on sheet {sheet_name!r}" if sheet_name else ""
    return {
        "status": "success",
        "message": f"Added slicer for {source_field!r} on {source_name!r}{on_sheet}.",
        "outputs": {"slicerName": slicer_name},
    }


registry.register("addSlicer", handler, mutates=True)
