apiVersion: v1
kind: Service
metadata:
  name: excel-assistant
  labels:
    app: excel-assistant
    app.kubernetes.io/name: excel-assistant
    app.kubernetes.io/part-of: ai-assistant-for-excel
spec:
  selector:
    app: excel-assistant
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
